source 'https://cdn.cocoapods.org/'

use_modular_headers!

target 'VizuryObjCSample' do
  # Pods for NotificationService
    platform :ios, '9.0'
    pod 'VizuryEventLogger'
end

target 'NotificationService' do
  # Pods for VizurySwiftSample
    platform :ios, '10.0'
    pod 'VizuryRichNotification'
end
