# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VizuryObjCSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VizuryObjCSample
    pod 'VizuryEventLogger'
    pod 'Firebase/Messaging'

end

target 'NotificationService' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VizuryObjCSample
    pod 'VizuryRichNotification'

end
